### ISSUE TITLE
[bug]pouchd start success but pouch ps failed

### ISSUE THREAD

**Issue by fanux** [alibaba/pouch#1487]
### Ⅰ. Issue Description
```
[root@compute065 shell]# pouch ps
Error: failed to get container list: Get http://d/v1.24/containers/json: dial unix /var/run/pouchd.sock: connect: connection refused
```

```
[root@compute065 ~]# pouchd -D
DEBU[0000] changing OOM score to -999
INFO[0000] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
INFO[0000] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.aufs  error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found.\n": exit status 1"
INFO[0000] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.zfs  error="path /var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
INFO[0000] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[0000] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
WARN[0000] could not use snapshotter aufs in metadata plugin  error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found.\n": exit status 1"
WARN[0000] could not use snapshotter zfs in metadata plugin  error="path /var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
INFO[0000] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1

INFO[0000] loading plugin "io.containerd.grpc.v1.cri"...  type=io.containerd.grpc.v1
INFO[0000] Start cri plugin with config {PluginConfig:{ContainerdConfig:{Snapshotter:overlayfs DefaultRuntime:{Type:io.containerd.runtime.v1.linux Engine: Root:} UntrustedWorkloadRuntime:{Type: Engine: Root:}} CniConfig:{NetworkPluginBinDir:/opt/cni/bin NetworkPluginConfDir:/etc/cni/net.d NetworkPluginConfTemplate:} Registry:{Mirrors:map[docker.io:{Endpoints:[https://registry-1.docker.io]} quay.io:{Endpoints:[http://172.16.59.153]}]} StreamServerAddress: StreamServerPort:10010 EnableSelinux:false SandboxImage:k8s.gcr.io/pause:3.1 StatsCollectPeriod:10 SystemdCgroup:false EnableTLSStreaming:false} ContainerdRootDir:/var/lib/pouch/containerd/root ContainerdEndpoint:/var/run/containerd.sock RootDir:/var/lib/pouch/containerd/root/io.containerd.grpc.v1.cri StateDir:/var/lib/pouch/containerd/state/io.containerd.grpc.v1.cri}
INFO[0000] Connect containerd service
INFO[0000] Get image filesystem path "/var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.overlayfs"
ERRO[0000] Failed to load cni during init, please check CRI plugin status before setting up network for pods  error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"
I0607 15:53:06.846452  420406 interface.go:360] Looking for default routes with IPv4 addresses
I0607 15:53:06.846506  420406 interface.go:365] Default route transits interface "enp26s0f2"
I0607 15:53:06.847818  420406 interface.go:174] Interface enp26s0f2 is up
I0607 15:53:06.847903  420406 interface.go:222] Interface "enp26s0f2" has 1 addresses :[172.29.101.132/24].
I0607 15:53:06.847932  420406 interface.go:189] Checking addr  172.29.101.132/24.
I0607 15:53:06.847950  420406 interface.go:196] IP found 172.29.101.132
I0607 15:53:06.847968  420406 interface.go:228] Found valid IPv4 address 172.29.101.132 for interface "enp26s0f2".

DEBU[2018-06-07T15:53:06.863608518+08:00] Get a grpc client                             elapsed=2.468µs
DEBU[2018-06-07T15:53:06.874576131+08:00] Get a grpc client                             elapsed=2.853µs
INFO[2018-06-07T15:53:06.87466065+08:00] start to subscribe io, backend: jsonfile, id: e0bc318076b06a3c3f83047897cee7463bb9185a0e683af536c04c4cf2135e68
INFO[2018-06-07T15:53:06.874680236+08:00] start to subscribe io, backend: jsonfile, id: e0bc318076b06a3c3f83047897cee7463bb9185a0e683af536c04c4cf2135e68
INFO[2018-06-07T15:53:06.919686835+08:00] success to add container, id: e0bc318076b06a3c3f83047897cee7463bb9185a0e683af536c04c4cf2135e68
INFO[2018-06-07T15:53:06.919720602+08:00] success to recover container: e0bc318076b06a3c3f83047897cee7463bb9185a0e683af536c04c4cf2135e68
DEBU[2018-06-07T15:53:06.920939984+08:00] Get a grpc client                             elapsed=3.085µs
INFO[2018-06-07T15:53:06.921041958+08:00] start to subscribe io, backend: jsonfile, id: c706158ec31da9b128a9fb8a2119ea591d485dd9c5fc8354f053c633489715e6
INFO[2018-06-07T15:53:06.921072047+08:00] start to subscribe io, backend: jsonfile, id: c706158ec31da9b128a9fb8a2119ea591d485dd9c5fc8354f053c633489715e6
DEBU[0000] garbage collected                             d=1.812982ms
INFO[2018-06-07T15:53:06.952303624+08:00] success to add container, id: c706158ec31da9b128a9fb8a2119ea591d485dd9c5fc8354f053c633489715e6
INFO[2018-06-07T15:53:06.952337207+08:00] success to recover container: c706158ec31da9b128a9fb8a2119ea591d485dd9c5fc8354f053c633489715e6
DEBU[2018-06-07T15:53:06.955617155+08:00] Get a grpc client                             elapsed=4.469µs
INFO[2018-06-07T15:53:06.955649536+08:00] start to subscribe io, backend: jsonfile, id: 5f99f2cb385a3f94d006180dc1ee3d9d96fc6616a3aa720f9fd25183c9424ee6
INFO[2018-06-07T15:53:06.955696311+08:00] start to subscribe io, backend: jsonfile, id: 5f99f2cb385a3f94d006180dc1ee3d9d96fc6616a3aa720f9fd25183c9424ee6
INFO[2018-06-07T15:53:06.988630906+08:00] success to add container, id: 5f99f2cb385a3f94d006180dc1ee3d9d96fc6616a3aa720f9fd25183c9424ee6
INFO[2018-06-07T15:53:06.988661325+08:00] success to recover container: 5f99f2cb385a3f94d006180dc1ee3d9d96fc6616a3aa720f9fd25183c9424ee6
DEBU[2018-06-07T15:53:06.989386549+08:00] Get a grpc client                             elapsed=2.754µs
INFO[2018-06-07T15:53:06.98940751+08:00] start to subscribe io, backend: jsonfile, id: a6c85ef2484569ef7a2557932b00492920390c9d54df9417b49e1f939bc97118
INFO[2018-06-07T15:53:06.989515904+08:00] start to subscribe io, backend: jsonfile, id: a6c85ef2484569ef7a2557932b00492920390c9d54df9417b49e1f939bc97118
```
Then Ctrl+C stop pouchd
```
^CWARN[2018-06-08T09:25:33.1076448+08:00] received signal: interrupt
DEBU[2018-06-08T09:25:33.107715631+08:00] Start cleanup containerd...
ERRO[2018-06-08T09:25:33.107969736+08:00] failed to recover container: a6c85ef2484569ef7a2557932b00492920390c9d54df9417b49e1f939bc97118,  failed to get task: transport is closing: unknown
INFO[2018-06-08T09:25:33.108032122+08:00] close containerio backend: jsonfile, id: a6c85ef2484569ef7a2557932b00492920390c9d54df9417b49e1f939bc97118
INFO[2018-06-08T09:25:33.108049525+08:00] close containerio backend: jsonfile, id: a6c85ef2484569ef7a2557932b00492920390c9d54df9417b49e1f939bc97118
INFO[2018-06-08T09:25:33.108045204+08:00] the task has quit, id: c706158ec31da9b128a9fb8a2119ea591d485dd9c5fc8354f053c633489715e6, err: rpc error: code = Internal desc = transport is closing, exitcode: 255, time: 0001-01-01 00:00:00 +0000 UTC
INFO[2018-06-08T09:25:33.107997727+08:00] the task has quit, id: 5f99f2cb385a3f94d006180dc1ee3d9d96fc6616a3aa720f9fd25183c9424ee6, err: rpc error: code = Internal desc = transport is closing, exitcode: 255, time: 0001-01-01 00:00:00 +0000 UTC
INFO[2018-06-08T09:25:33.108063321+08:00] finished to subscribe io, backend: jsonfile, id: a6c85ef2484569ef7a2557932b00492920390c9d54df9417b49e1f939bc97118
INFO[2018-06-08T09:25:33.107980401+08:00] the task has quit, id: e0bc318076b06a3c3f83047897cee7463bb9185a0e683af536c04c4cf2135e68, err: rpc error: code = Internal desc = transport is closing, exitcode: 255, time: 0001-01-01 00:00:00 +0000 UTC
INFO[2018-06-08T09:25:33.108108318+08:00] finished to subscribe io, backend: jsonfile, id: a6c85ef2484569ef7a2557932b00492920390c9d54df9417b49e1f939bc97118
DEBU[63146] received signal                               signal=terminated
INFO[63146] Stop CRI service
ERRO[63146] Failed to handle event stream                 error=<nil>
INFO[63146] Stop CRI service
INFO[63146] Event monitor stopped
DEBU[2018-06-08T09:25:33.109016427+08:00] Get a grpc client                             elapsed=3.382µs
ERRO[2018-06-08T09:25:33.109173637+08:00] failed to recover container: efd4beaef0ff75b35866dffa6be352b03597c6190ae662b5a3122f1be7cc3ea3,  failed to load container: grpc: the client connection is closing: failed precondition
INFO[2018-06-08T09:25:33.109211406+08:00] close containerio backend: jsonfile, id: efd4beaef0ff75b35866dffa6be352b03597c6190ae662b5a3122f1be7cc3ea3
INFO[2018-06-08T09:25:33.109205619+08:00] start to subscribe io, backend: jsonfile, id: efd4beaef0ff75b35866dffa6be352b03597c6190ae662b5a3122f1be7cc3ea3

DEBU[2018-06-08T09:25:33.214065647+08:00] Endpoint (8f4e88a) restored to network (636c66d)
DEBU[2018-06-08T09:25:33.231821983+08:00] Allocating IPv4 pools for network bridge (636c66db128e49b8ef563694d1eb28684485e0855618e106cd5041cc2a86304a)
DEBU[2018-06-08T09:25:33.231864608+08:00] RequestPool(LocalDefault, 172.17.0.1/24, , map[], false)
DEBU[2018-06-08T09:25:33.231920053+08:00] RequestAddress(LocalDefault/172.17.0.0/24, 172.17.0.1, map[RequestAddressType:com.docker.network.gateway])
DEBU[2018-06-08T09:25:33.23295689+08:00] Assigning addresses for endpoint c706158e's interface on network bridge
DEBU[2018-06-08T09:25:33.232987953+08:00] RequestAddress(LocalDefault/172.17.0.0/24, 172.17.0.6, map[])
DEBU[2018-06-08T09:25:33.233021609+08:00] Assigning addresses for endpoint a6c85ef2's interface on network bridge
DEBU[2018-06-08T09:25:33.233039235+08:00] RequestAddress(LocalDefault/172.17.0.0/24, 172.17.0.2, map[])
DEBU[2018-06-08T09:25:33.233059581+08:00] Assigning addresses for endpoint efd4beae's interface on network bridge
DEBU[2018-06-08T09:25:33.233075739+08:00] RequestAddress(LocalDefault/172.17.0.0/24, 172.17.0.3, map[])
DEBU[2018-06-08T09:25:33.233095021+08:00] Assigning addresses for endpoint e0bc3180's interface on network bridge
DEBU[2018-06-08T09:25:33.233111947+08:00] RequestAddress(LocalDefault/172.17.0.0/24, 172.17.0.5, map[])
DEBU[2018-06-08T09:25:33.233131862+08:00] Assigning addresses for endpoint 5f99f2cb's interface on network bridge
DEBU[2018-06-08T09:25:33.233147407+08:00] RequestAddress(LocalDefault/172.17.0.0/24, 172.17.0.4, map[])
INFO[0000] Firewalld running: false
INFO[0000] Firewalld running: false
INFO[0000] Firewalld running: false
INFO[0000] Firewalld running: false
INFO[0000] Firewalld running: false
WARN[2018-06-08T09:25:33.902948643+08:00] There are old containers, don't to initialize network
INFO[2018-06-08T09:25:33.912311715+08:00] start to listen to: tcp://0.0.0.0:8021
INFO[2018-06-08T09:25:33.912449603+08:00] start to listen to: unix:///var/run/pouchd.sock
```
### Ⅳ. How to reproduce it (as minimally and precisely as possible)
Unknow how to reproduce, I just run some container with lxcfs, and using runv，At first it was good before I  enable CRI

- pouch version (use `pouch version`):
[root@compute065 hyperstart]# pouch version
GoVersion:       go1.9.1
KernelVersion:   4.16.13-1.el7.elrepo.x86_64
Os:              linux
Version:         0.5.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-05-24T11:20:02+00:00
GitCommit:       0.4.0-297-g17d62f9
- OS (e.g. from /etc/os-release):
CentOS Linux release 7.5.1804 (Core)
- Kernel (e.g. `uname -a`):
Linux compute065.sha.openstack 4.16.13-1.el7.elrepo.x86_64 #1 SMP Wed May 30 14:31:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others:
qemu-x86_64 -version
qemu-x86_64 version 2.0.0, Copyright (c) 2003-2008 Fabrice Bellard
- runv version:
 runv version 1.0.0, commit: v1.0.0

**Comment by HusterWan** [comment]
@fanux Thanks a lot for your feedback, we will fix this problem soon.

**Comment by fuweid** [comment]
I think we can add the version of the containerd so that we can have more information during debug. I meet the hang before cause by using containerd v1.0.0. @fanux Could you mind to provide about containerd version part information? thanks 😄

**Comment by HusterWan** [comment]
containerd stuck at : 

```
goroutine 169 [select, 5 minutes]:
github.com/containerd/containerd/vendor/github.com/stevvooe/ttrpc.(*Client).dispatch(0xc420264960, 0x5567009c45a0, 0xc420437b00, 0xc4203854c0, 0xc4203e89c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/containerd/containerd/vendor/github.com/stevvooe/ttrpc/client.go:102 +0x282
github.com/containerd/containerd/vendor/github.com/stevvooe/ttrpc.(*Client).Call(0xc420264960, 0x5567009c45a0, 0xc420437b00, 0x55670012f47d, 0x25, 0x556700113e48, 0x5, 0x556700599da0, 0xc420274490, 0x556700599e80, ...)
	/home/travis/gopath/src/github.com/containerd/containerd/vendor/github.com/stevvooe/ttrpc/client.go:73 +0x15d
github.com/containerd/containerd/linux/shim/v1.(*shimClient).State(0xc42000e118, 0x5567009c45a0, 0xc420437b00, 0xc420274490, 0x0, 0x5566ffa5b85f, 0x556700516580)
	/home/travis/gopath/src/github.com/containerd/containerd/linux/shim/v1/shim.pb.go:1729 +0xbf
github.com/containerd/containerd/linux.(*Task).State(0xc42032b490, 0x5567009c45a0, 0xc420437b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/containerd/containerd/linux/task.go:107 +0xc4
github.com/containerd/containerd/services/tasks.processFromContainerd(0x7f8e55cb0408, 0xc420437b00, 0x7f8e55cb4f80, 0xc42032b490, 0xc42032b490, 0x5567009c97c0, 0xc42032b490)
	/home/travis/gopath/src/github.com/containerd/containerd/services/tasks/service.go:225 +0xbe
github.com/containerd/containerd/services/tasks.(*service).Get(0xc4203bfb30, 0x7f8e55cb0408, 0xc420437b00, 0xc4203e8640, 0xc4203bfb30, 0x55670013061d, 0x3)
	/home/travis/gopath/src/github.com/containerd/containerd/services/tasks/service.go:268 +0xef
github.com/containerd/containerd/api/services/tasks/v1._Tasks_Get_Handler.func1(0x7f8e55cb0408, 0xc420437b00, 0x556700597800, 0xc4203e8640, 0xc4202c34f0, 0x556700a21bb8, 0x5567004da2a0, 0xc420274480)
	/home/travis/gopath/src/github.com/containerd/containerd/api/services/tasks/v1/tasks.pb.go:680 +0x88
github.com/containerd/containerd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.UnaryServerInterceptor(0x7f8e55cb0408, 0xc420437b00, 0x556700597800, 0xc4203e8640, 0xc4203e8680, 0xc4203e86c0, 0x50, 0x48, 0xc4203e8600, 0xc4203f7968)
	/home/travis/gopath/src/github.com/containerd/containerd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go:29 +0xd4
github.com/containerd/containerd/server.interceptor(0x7f8e55cb0408, 0xc420437a40, 0x556700597800, 0xc4203e8640, 0xc4203e8680, 0xc4203e86c0, 0x1, 0xc4203f79e0, 0x5566ffa1774a, 0x50)
	/home/travis/gopath/src/github.com/containerd/containerd/server/server.go:267 +0x1d2
github.com/containerd/containerd/api/services/tasks/v1._Tasks_Get_Handler(0x5567005eb4a0, 0xc4203bfb30, 0x7f8e55cb0408, 0xc4202451d0, 0xc4202c3400, 0x556700602ee0, 0x0, 0x0, 0x5566ffea803a, 0xc42020ea60)
	/home/travis/gopath/src/github.com/containerd/containerd/api/services/tasks/v1/tasks.pb.go:682 +0x16f
github.com/containerd/containerd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420115a40, 0x5567009c76e0, 0xc420134160, 0xc42035a900, 0xc4204444b0, 0x5567009aed80, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/containerd/containerd/vendor/google.golang.org/grpc/server.go:826 +0xab6
github.com/containerd/containerd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420115a40, 0x5567009c76e0, 0xc420134160, 0xc42035a900, 0x0)
	/home/travis/gopath/src/github.com/containerd/containerd/vendor/google.golang.org/grpc/server.go:1023 +0x152a
github.com/containerd/containerd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4200d8050, 0xc420115a40, 0x5567009c76e0, 0xc420134160, 0xc42035a900)
	/home/travis/gopath/src/github.com/containerd/containerd/vendor/google.golang.org/grpc/server.go:572 +0xa1
created by github.com/containerd/containerd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/travis/gopath/src/github.com/containerd/containerd/vendor/google.golang.org/grpc/server.go:570 +0xa3

```

**Comment by fuweid** [comment]
we will keep eyes on this issue.
