### ISSUE TITLE
[bug] pouch pull can't be run by using exec package

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#313]
**Issue Description**
When call `pouch pull` in go package exec, it will panic.

**Describe what happened**:
```
pouch_cli_create_test.go:28:
    RunCmd(c, &cmd)
lib_common.go:108:
    c.Assert(ret.ExitCode, check.Equals, 0,
        check.Commentf("[FAIL]: CMD[%s %s] return %d,\n"+
            "Stdout: %s\n Stderr: %s",
            cmd.binary, cmd.args, ret.ExitCode, ret.Stdout(), ret.Stderr()))
... obtained int = 2
... expected int = 0
... [FAIL]: CMD[/usr/local/bin/pouch [pull registry.hub.docker.com/library/busybox:latest]] return 2,
Stdout:
 Stderr: panic: provided file is not a console

goroutine 1 [running]:
github.com/alibaba/pouch/vendor/github.com/containerd/console.Current(0xc420288000, 0x0)
	/home/sit/letty/src/github.com/alibaba/pouch/vendor/github.com/containerd/console/console.go:51 +0x71
github.com/alibaba/pouch/vendor/github.com/containerd/containerd/progress.(*Writer).Flush(0xc420288000, 0x0, 0x0)
	/home/sit/letty/src/github.com/alibaba/pouch/vendor/github.com/containerd/containerd/progress/writer.go:49 +0x5e
main.renderOutput(0x13aecc0, 0xc4203a6100, 0xc4203a6100, 0x7ffd71d9c538)
	/home/sit/letty/src/github.com/alibaba/pouch/cli/pull.go:93 +0x1ef
main.(*PullCommand).runPull(0xc42043dd00, 0xc420400100, 0x1, 0x1, 0x0, 0x0)
	/home/sit/letty/src/github.com/alibaba/pouch/cli/pull.go:64 +0x231
main.(*PullCommand).Init.func1(0xc42020fb00, 0xc420400100, 0x1, 0x1, 0x0, 0x0)
	/home/sit/letty/src/github.com/alibaba/pouch/cli/pull.go:38 +0x48
github.com/alibaba/pouch/vendor/github.com/spf13/cobra.(*Command).execute(0xc42020fb00, 0xc4204000c0, 0x1, 0x1, 0xc42020fb00, 0xc4204000c0)
	/home/sit/letty/src/github.com/alibaba/pouch/vendor/github.com/spf13/cobra/command.go:742 +0x49b
github.com/alibaba/pouch/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42020f680, 0xc420549ed0, 0x1, 0x1)
	/home/sit/letty/src/github.com/alibaba/pouch/vendor/github.com/spf13/cobra/command.go:827 +0x30e
github.com/alibaba/pouch/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42020f680, 0x1, 0xc420400050)
	/home/sit/letty/src/github.com/alibaba/pouch/vendor/github.com/spf13/cobra/command.go:780 +0x2b
main.(*Cli).Run(0xc420123560, 0x13ae800, 0xc42043dcf0)
	/home/sit/letty/src/github.com/alibaba/pouch/cli/cli.go:78 +0x2f
main.main()
	/home/sit/letty/src/github.com/alibaba/pouch/cli/main.go:34 +0x560
```
**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by skoo87** [comment]
I will fix it, I think I know the reason for the panic.

**Comment by skoo87** [comment]
this is because "pouch pull" not run in a console.  We depend on containerd's progress to implement the "pull" command, I find that the containerd's progress can work in a console only, not work via exec. 

https://github.com/containerd/containerd/blob/master/progress/writer.go#L49 。

I think I will find a way to fix it.

**Comment by 0x04C2** [comment]
Yes. I comment the `fw.Flush()` for local test. I'm curious about CI.

I think we should wrap the output and do some thing if the stdout is not pty/tty.
